default:
  LOG_LEVEL: "info"
  DEEPSEEK_API_URL: "https://api.deepseek.com/v1"
  DEEPSEEK_API_KEY: "sk-a17c861e74ce49c6878efcae740baeed"
  ARK_API_KEY: "f43df693-455a-4e3e-b987-d76d7b57f4c3"
  ARK_API_URL: "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
  ARK_BASE_URL: "https://ark.cn-beijing.volces.com/api/v3"
  DASHSCOPE_API_KEY: "sk-4ef42187cc2e47999d0c835c10fc5a78" 
  DASHSCOPE_BASE_URL: https://dashscope.aliyuncs.com/compatible-mode/v1
  QWEN_API_URL: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  OPENIAI_BASE_URL: "https://api.qhaigc.net"
  OPENIAI_API_KEY: ""
  REDIS_HOST: 118.190.155.195
  REDIS_PORT: 6379
  REDIS_DB: 15
  REDIS_AUTH: "fwo42fql"
  score_threshold: 1.75
  rerank: false
  embedding_model: "doubao"
  LOG_REDIS_HOST: "r-8vbmz6jkq5smozysiipd.redis.zhangbei.rds.aliyuncs.com"
  LOG_REDIS_PORT: 63791
  LOG_REDIS_DB: 4
  LOG_REDIS_AUTH: "Xlys!@#456qwe"
  min_connections: 1  # 最小连接数
  max_connections: 10  # 最大连接数
  socket_connect_timeout: 15.0  # 连接超时时间
  socket_timeout: 5.0  # 等待超时时间
  max_idle_time: 60  # 最大空闲时间
  env_version: "alpha"
  # ES
  ES_HOST: es-cn-8qq47vdfe0005swll.public.elasticsearch.aliyuncs.com
  ES_PORT: 9200
  ES_USER: elastic
  ES_AUTH: fh6u65tPxSa@fbcv1pM
  # search doctor
  DOCTOR_SEARCH_URL: "https://api-backend.sihuiyiliao.com/doctor_service/api/doctor/coze/doctors"
  IS_LOCAL: false
  chat_history_num: 8
  CHUNK_SIZE: 2
  special_punctuation: '▢|▶|❗|📞'
  QA_SIZE: 30
  QA_ANSWER_SIZE: 10
  DEFAULT_DOCTOR_IDS: [42,769,527,425,1111,1118]
  USE_BGE_CODE: false
  USE_RANK: true

  # emr
  # videoagent
  IMAGE_GENERATE_MODEL: doubao-seedream-4-0-250828
  IMAGE_DESCRIBE_MODEL: doubao-1-5-vision-pro-32k-250115
  VIDEO_GENERATE_MODEL: "doubao-seedance-1-0-pro-250528"
  QWEN_IMAGE_DESCRIBE_MODEL: "qwen-vl-max"
  QWEN_IMAGE_GENERATE_MODEL: "wan2.2-t2i-plus" #通义万相2.2-文生图-Plus
  QWEN_VIDEO_GENERATE_MODEL: "wan2.2-i2v-plus" #通义万相2.2-图生视频-Plus




